### ISSUE TITLE
Float types are not supported

### ISSUE THREAD

**Issue by igor-plotnikov** [snorwin/jsonpatch#13]
Float types are not supported,  comparing JSON with a float type throws an error

**Comment by igor-plotnikov** [comment]
Add a case for floats to walker.go:

		if modified.Bool() != current.Bool() {
			w.replace(pointer, modified.Bool(), current.Bool())
		}
	case reflect.Float64, reflect.Float32:
		if modified.Float() != current.Float() {
			w.replace(pointer, modified.Float(), current.Float())
		}		
	case reflect.Invalid:
		// undefined interfaces are ignored for now
		return nil
		
and to patch_test.go:

	Uint32  uint32  `json:"uint32"`
	Uint64  uint64  `json:"uint64"`
	UintPtr uintptr `json:"ptr" faker:"-"`
	Float32   float32   `json:"float32"`
	Float64   float64   `json:"float64"`
}

It works for me.

**Comment by snorwin** [comment]
Hi @igor-plotnikov,
Thank you for submitting an issue, feel free to create a pull request with the suggested changes.

Cheers,
Norwin

**Comment by igor-plotnikov** [comment]
Norwin,

I've tried to create a branch with the fix, but I don't have the write
rights for your repository

Regards
Igor

**Comment by snorwin** [comment]
You need to create a fork first (https://docs.github.com/en/get-started/quickstart/fork-a-repo). On you personal fork you then can create branches and PR to the main branch of this repo here.

**Comment by johanneswuerbach** [comment]
@snorwin would you have time to look into any of the provided PRs. That would be amazing 🤩
